export const ACTION_TYPE = {
	SET_USER_DATA: 'SET_USER_DATA',
	LOGOUT: 'LOGOUT',
	TOGGLE_MODAL: 'TOGGLE_MODAL',
	SET_PROJECT_DATA: 'SET_PROJECT_DATA',
	RESET_PROJECT_DATA: 'RESET_PROJECT_DATA',
	SET_PROJECT_TYPE: 'SET_PROJECT_TYPE',
};
